import {} from './boolean.test';
import {} from './currency.test';
import {} from './date.test';
import {} from './datetime.test';
import {} from './entity.test';
import {} from './numberOfInstances.test';
import {} from './options.test';
import {} from './text.test';
import {} from './time.test';
